//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Decorators
    {
        public int ID_decorator { get; set; }
        public string FIO { get; set; }
        public string telephon { get; set; }
        public string decorator_adress { get; set; }
        public int ID_education { get; set; }
    
        public virtual Education Education { get; set; }
    }
}
