//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parks
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ParksEntities : DbContext
    {
        public ParksEntities()
            : base("name=ParksEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Decorators> Decorators { get; set; }
        public virtual DbSet<Education> Education { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Firm> Firm { get; set; }
        public virtual DbSet<Plants> Plants { get; set; }
        public virtual DbSet<PlantSpecies> PlantSpecies { get; set; }
        public virtual DbSet<Services> Services { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<WateringMode> WateringMode { get; set; }
        public virtual DbSet<WorkSchedule> WorkSchedule { get; set; }
        public virtual DbSet<Zones> Zones { get; set; }
    }
}
