//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parks
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkSchedule
    {
        public int ID_schedule { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public int ID_employee { get; set; }
        public int ID_plant { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Plants Plants { get; set; }
    }
}
