//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parks
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zones
    {
        public int ID_zone { get; set; }
        public string zone_name { get; set; }
        public int ID_plant { get; set; }
    
        public virtual Plants Plants { get; set; }
    }
}
